server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

camel:
  components:
    kafka:
      brokers: localhost:9092
      consumer:
        group-id: demo-2
  springboot:
    main-run-controller: true

aggregation:
  size: 10 # Configurable aggregation size
  timeout: 10000 # Configurable aggregation timeout in milliseconds

output:
  directory: C:/Users/risha/Downloads/AggregatedFiles # Configurable output directory